//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFilling_KP_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentLetter
    {
        public System.Guid ID { get; set; }
        public string Document_Created_By_ID { get; set; }
        public string Number { get; set; }
        public string Document_From { get; set; }
        public string Origin_Agency { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime Created_Date { get; set; }
    }
}
